site_name: MiniSub

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  analytics:
    provider: google
    property: G-C7R8944FZY
  consent:
    cookies:
      analytics:
        name: Google Analytics
        checked: false