- name: Add ROS apt key to keyring file
  apt_key:
    url: "{{ minisub_ros_key_url }}"
    keyring: "{{ minisub_ros_keyring }}"
    state: present

- name: Add ROS apt repository
  vars:
    arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' if ansible_architecture == 'aarch64' else ansible_architecture }}"
  apt_repository:
    repo: "deb [arch={{ arch }} signed-by={{ minisub_ros_keyring }}] {{ minisub_ros_repo }} {{ hostvars[inventory_hostname]['ansible_facts']['distribution_release'] }} main"
    state: present

- name: Install ROS apt packages {{ minisub_ros_packages | join(', ') }}
  apt:
    state: present
    name: "{{ minisub_ros_packages }}"
