- name: Update apt packages
  apt:
    name: "*"
    state: latest
    update_cache: true

- name: Install system base packages {{ minisub_base_packages | join(', ') }}
  apt:
    state: present
    name: "{{ minisub_base_packages }}"

- name: Install pip packages
  pip: 
    state: present
    name: "{{ minisub_pip_packages }}"