- name: Add Vulcanexus Micro ROS apt key to keyring file
  apt_key:
    url: "{{  minisub_vcx_uros_key_url }}"
    keyring: "{{  minisub_vcx_uros_keyring }}"
    state: present

- name: Add Vulcanexus Micro ROS apt repository
  vars:
    arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' if ansible_architecture == 'aarch64' else ansible_architecture }}"
  apt_repository:
    repo: "deb [arch={{ arch }} signed-by={{ minisub_vcx_uros_keyring }}] {{ minisub_vcx_uros_repo }} {{ hostvars[inventory_hostname]['ansible_facts']['distribution_release'] }} main"
    state: present

- name: Install Vulcanexus Micro ROS apt packages {{ minisub_vcx_uros_packages | join(', ') }}
  apt:
    state: present
    name: "{{ minisub_vcx_uros_packages }}"
