version: "2"

volumes:
  prom-data:

services:
  uros-agent:
    image: microros/micro-ros-agent:galactic
    command: udp4 -p 8888
    network_mode: host
    restart: always
  
  ros1-master:
    image: ros:noetic-ros-core
    command: roscore
    network_mode: host
    restart: always

  ros1-bridge:
    depends_on: 
    - ros1-master
    image: ros:galactic-ros1-bridge
    command: ros2 run ros1_bridge dynamic_bridge --bridge-all-topics
    network_mode: host
    restart: always

  ros-ws-bridge:
    image: ryanfriedman/rosbridge-server:galactic_arm64
    network_mode: host
    restart: always

  metric-exporter:
    image: jeffreydd/minisub-metric-exporter:latest
    network_mode: host
    restart: always

  prom:
    image: prom/prometheus
    volumes:
    - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    - prom-data:/prometheus/
    ports:
    - 9000:9090
    restart: always

  minisub-ui:
    image: jeffreydd/minisub-ui
    ports:
    - 8080:80
    restart: always