- hosts: localhost
  become: true
  roles:
  - role: jeffreydd.minisub.base
  - role: jeffreydd.minisub.desktop

- name: Setup VirtualBox guest additions
  hosts: localhost
  become: true
  vars:
    virtualbox_version: 6.1.34
  tasks:

  - when: "ansible_virtualization_type == 'virtualbox'"
    block: 
    - shell: ansible-galaxy install PeterMosmans.virtualbox-guest

    - include_role: 
        name: PeterMosmans.virtualbox-guest
